import os
os.eniron.setdefault('DJANGO_SETTINGS_MODULE',
                     'wad2_group_project.settings')
from gymbuddy.models import Gym, ProgressPics, Profile, Comments
import django
django.setup()

def populate():
    Profile=[
        {"username": "spic99",
         "email": "2324936c@student.gla.ac.uk",
         "password": "Glasgow617",
         "AboutMe": "I'm 20 years old and just moved to Glasgow for university. I'm relatively new to the world of fitness and would like to find an affordable nearby gym with good user ratings. I'd also like to find a more experienced partner to help show me the ropes.",
         "Following": "james1, K3lly, pdevanney",
         "ProfilePicture": "",
         "GymID": "1",
         "Height": "118",
         "Weight": "72",
         "Dob": "18/02/1999",
         "Experience": "Beginner"},
        {"username": "K3LLy",
         "email": "kellys1@gmail.com",
         "password": "K311y1",
         "AboutMe": "I'm 40 years old living in the West End of Glasgow. Veteran Powerlifter with a keen eye for strength. Looking for an equally determined training partner who can spot me and take pictures of my lifting. Hit me up if interested.",
         "Following": "frankie1, ab123, steg_3, jonny12, jamesmaddis0n",
         "ProfilePicture": "",
         "GymID": "2",
         "Height": "100",
         "Weight": "85",
         "Dob": "17/01/1979",
         "Experience": "Advanced"},
        {"username": "ab96",
         "email": "annab87@outlook.com",
         "password": "Celtic67",
         "AboutMe": "22. Glasgow. Puregym. Usually in gym between 6 and 7 most evenings. Hmu if you want to go together.",
         "Following": "nickfitness, orla_puregym, oli_s00",
         "ProfilePicture": "",
         "GymID": "3",
         "Height": "162",
         "Weight": "55",
         "Dob": "17/12/1996",
         "Experience": "Intermediate"},
        {"username": "aidan67",
         "email": "aidsboy67@outlook.com",
         "password": "Lisbon67",
         "AboutMe": "Keen rugby player and enjoy heavy lifting in spair time. Let me know what you think of my progress pics. open to any tips you may have.",
         "Following": "rugby01, james21, dany99, gord0n2, l1fts3, Xperience, k3LLy, spic99",
         "ProfilePicture": "",
         "GymID": "3",
         "Height": "200",
         "Weight": "115",
         "Dob": "02/10/1997",
         "Experience": "Intermediate"}
        {"username": "frankub07",
         "email": "frankrfc@outlook.com",
         "password": "St3veG123",
         "AboutMe": "Frank, Glasgow, 32. Member of Snap Fitness, due to work usually only in at weekends during the day. Always open to meeting new people and a gym buddy. I like to keep fit but don't lift too heavy weights so might not suit everyone. Let us know if you are interested.",
         "Following": "steg_3, cr7",
         "ProfilePicture": "",
         "GymID": "4",
         "Height": "183",
         "Weight": "78",
         "Dob": "17/05/1986",
         "Experience": "Intermediate"}
    ]