# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('GymID', models.AutoField(primary_key=True, serialize=False)),
                ('GymName', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=30)),
                ('X_Coord', models.DecimalField(decimal_places=6, max_digits=9, max_length=10)),
                ('Y_Coord', models.DecimalField(decimal_places=6, max_digits=9, max_length=10)),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=4, max_length=3)),
                ('OpeningHours', models.CharField(max_length=50)),
                ('Users', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
