# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 22:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.CharField(max_length=30, unique=True)),
                ('Date', models.DateField(max_length=128, unique=True)),
                ('Comment', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressPics',
            fields=[
                ('UserName', models.CharField(max_length=15, unique=True)),
                ('PhotoID', models.AutoField(primary_key=True, serialize=False)),
                ('Photo', models.ImageField(blank=True, upload_to='progress_pics')),
                ('Likes', models.IntegerField(default=0)),
                ('comments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbuddy.Comments')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='UserName',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Experience',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=12),
        ),
    ]
