# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0003_auto_20190304_2247'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='gym',
            options={'verbose_name_plural': 'Gyms'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='progresspics',
            options={'verbose_name_plural': 'ProgressPics'},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='User',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='id',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='GymID',
        ),
        migrations.RemoveField(
            model_name='gym',
            name='Users',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='UserID',
        ),
        migrations.RemoveField(
            model_name='progresspics',
            name='comments',
        ),
        migrations.AddField(
            model_name='comments',
            name='CommentID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='OnPic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymbuddy.ProgressPics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='Poster',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gymbuddy.Profile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gym',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comments',
            name='Comment',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateField(max_length=128),
        ),
        migrations.AlterField(
            model_name='profile',
            name='AboutMe',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Height',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=3),
        ),
        migrations.AlterField(
            model_name='progresspics',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
