# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0004_auto_20190305_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='AboutMe',
            field=models.TextField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Following',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='GymID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gymbuddy.Gym'),
        ),
        migrations.AlterField(
            model_name='progresspics',
            name='Photo',
            field=models.ImageField(upload_to='progress_pics'),
        ),
    ]
