# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-18 23:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0005_auto_20190318_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Following',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='progresspics',
            name='UserName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gymbuddy.Profile'),
        ),
    ]
