# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0007_auto_20190319_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
