# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0008_gym_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
