# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-19 18:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0011_auto_20190319_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
