# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0012_auto_20190319_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='gym',
            name='WebsiteURL',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
