# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0018_auto_20190320_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='GymID',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='gymbuddy.Gym'),
            preserve_default=False,
        ),
    ]
