# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0020_auto_20190320_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Height',
            field=models.DecimalField(decimal_places=2, max_digits=5, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Weight',
            field=models.IntegerField(null=True),
        ),
    ]
