# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0022_profile_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
