# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 17:53
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0022_profile_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='user.username', unique=True),
        ),
    ]
