# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-20 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gymbuddy', '0023_auto_20190320_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='slug',
        ),
    ]
